title: openSUSE Kubic
name: Kubic
email: opensuse-factory@opensuse.org
description: Certified Kubernetes distribution & container-related technologies built by the openSUSE community
baseurl: ""
url: ""
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 7
paginate_path: "/blog/page:num/"

permalink: /blog/:year-:month-:day-:title/

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

